### ISSUE TITLE
a question for html <base> and custom link

### ISSUE THREAD

**Issue by Coulsite** [Astremy/SAPAS#5]
Hello, I would like to know if it is possible to use `<base>` which is in "html" in the python.
I mean change the localhost to a custom link.

`<! DOCTYPE html>`
`< html >`
`<base href="https://www.word.com">`
`</ html >`

`
site = Server("0.0.0.0,80")
`
`
@site.path("https://www.word.com/page")
def page:
    return template("page.html")
`
I tried, but I saw that it didn't work.
I don't know myself very well in python unfortunately at the moment.

**Comment by Astremy** [comment]
You're in the bad way to use DNS, and your code contain a lot of problems :

You doesn't have declared properly the function page (need brace)
Server take 2 arguments, the host and after the port
A path is the path AFTER the DN (Domain Name)
For the DN, we doesn't need the protocol ("https://")

And finally, the DNS don't work like that, learn about if you want to have a custom domain.
The localhost, like the name says, is the host local of your computer, use DNS is different of just change host.
